### PR TITLE
2019.11 bump

### PR DESCRIPTION
**Pull request by NickJosevski**
merge just before we tag

TODO: nick can we have more whitelist so this can merge earlier?

### CODE REVIEW

**Comment by NickJosevski** [comment]
@flin-8 can you make sure this gets merged before client goes out, I'll be AFK at some point this arvo

**Comment by NickJosevski** [comment]
oh really? I shipped that whitelist thing over a week ago, I can look at that later if it is still broken...

**Comment by flin-8** [comment]
> @flin-8 can you make sure this gets merged before client goes out, I'll be AFK at some point this arvo

Merged to `master`?

**Comment by NickJosevski** [comment]
Correct merge to vnext and then to master, any order

**Pull request merged**
